language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
# script: ./map-matching.sh action=test
notifications:
  email:
    - github@graphhopper.com

# enable container-based stack
sudo: false
