graphhopper:
  datareader.file: map-data/leipzig_germany.osm.pbf # OSM input file (example data)
  graph.location: graph-cache
  graph.flag_encoders: car
  prepare.ch.weightings: no

server:
  applicationConnectors:
  - type: http
    port: 8989
  adminConnectors:
  - type: http
    port: 8990
